### ISSUE TITLE
Versioning the downloadable binaries

### ISSUE THREAD

**Issue by weiwenweiwen** [moonbitlang/moonbit-docs#131]
Now we can only download the latest version from URLs like https://cli.moonbitlang.cn/ubuntu_x86/moonc.

This is not friendly to some distribution packaging. For example, the Nix system requires the corresponding SHA-256 hash for each downloaded binary files. When the `moonc` file has been updated but the download URL remains, it might cause build failure in  at an indeterminate time.

If we have versioned URL https://cli.moonbitlang.cn/ubuntu_x86/moonc-v0.1.1, the file hash should always remain the same.

**Comment by bobzhang** [comment]
Thanks for your interest in MoonBit, note moonbit is changing too fast that it is not yet ready for distribution packaging, we expect it will become stable by the mid of this year, afterwards, we we will provide versioned URL

**Comment by chawyehsu** [comment]
> moonbit is changing too fast that it is not yet ready for distribution packaging

@bobzhang This makes sense, but btw could you provide a bundled zip, like `moon-nightly.zip`, rather than the install script of the toolchain even if it's currently in heavy development? I find it's hard for me to track the latest and updated moonbit toolchain using the script on https://www.moonbitlang.com/download/. The provided shell script is problematic for me and I tend to avoid using it. I'm currently using bare curl commands to gather these isolated binaries...
