### ISSUE TITLE
[Feature reuest] To allow write in struct methods inside struct

### ISSUE THREAD

**Issue by DmitrijOkeanij** [moonbitlang/moonbit-docs#334]
Feature reuest to allow to write methods related on struct inside struct block, like in others language.

```
struct Xxx {
   id: Int
   ...
   pub fn() -> Unit {
      println(self.id)
      ...
   }
}
```

And the second, may be to allow just not to write -> Unit if function not return value and allow short code like this as syntax shugar
```
pub fn()  {
      println("Hi")
   }
```

**Comment by peter-jerry-ye** [comment]
These are unlikely to be implemented because it contradicts with the language design.

For the first question, we designed so that the language is flattened, and each toplevel object can be isolated from each other, for better AI code generation and for readability. Same applies to the second question, we demand top-level type to be clearly defined so that it serves as documentation itself.
